Basically this python file describes two functions giving the implementation of function and gradient of a random function from rastrigin family

first we randomly generate 3 matrices A, B, C from gaussian dist of N(0, 1) and and generate function and grad accordingly

In [1]:
import pandas as pd
import numpy as np
import math


In [3]:
n = 3

In [ ]:
A = np.random.normal(0, 1, size=(n, n))
A

array([[-0.13389709,  0.66033709, -0.83107491],
       [ 0.34931319,  0.5813902 ,  0.7955751 ],
       [-1.25466644, -0.92994163, -0.08926512]])

In [ ]:
B = np.random.normal(0, 1, size=(n, 1))
B

array([[-0.11657359],
       [-0.87523414],
       [-0.69550149]])

In [ ]:
C = np.random.normal(0, 1, size=(1, n))
C

array([[-0.08322539, -0.11579539,  0.15980686]])

In [4]:
A = np.random.normal(0, 1, size=(n, n))
B = np.random.normal(0, 1, size=(n, 1))
C = np.random.normal(0, 1, size=(1, n))

In [5]:
#defining parameters
# func is 1/2 * (A * X - B) ** 2 - sum(C * cos(2pi * x)) + 3
def function(cord, A, B, C):
  n = cord.shape[0]
  cord = np.atleast_2d(cord).T  #Transpose
  res = np.linalg.norm( A@cord - B )
  res = 0.5 * (res ** 2)
  angle = np.array(2 * math.pi * cord)
  tri = C@np.cos(angle)
  res = res - tri + n
  return res[0][0]

X = np.array([1, 1, 1])
function(X, A, B, C)

25.49986034475729

In [27]:
def grad(cord, A, B, C):
  n = cord.shape[0]
  cord = np.atleast_2d(cord).T  #Transpose
  Anew = A.copy()
  res = Anew@cord - B
  res = np.append(res, [[2 * math.pi]])
  tri = np.sin(2 * math.pi * cord)
  C = np.atleast_2d(C).T
  a = np.multiply(tri, C)
  # print(a)
  # val = np.full((n, 1), a[0][0])
  Anew = np.hstack((Anew, a))
  # print(Anew)
  res = Anew@res
  return res

X = np.array([1, 1, 1])
k=grad(X , A, B, C)
print(k)

[5.26651329 2.74362841 2.00323345]


In [ ]:
type(k)

numpy.ndarray

In [28]:
A = np.random.normal(0, 1, size=(n, n))
B = np.random.normal(0, 1, size=(n, 1))
C = np.random.normal(0, 1, size=(1, n))
error = 1000
print(np.sin(math.pi / 2))
tolerance = 1
x = np.array([100, 100, 100])
print(x)
fval = []
yval = []

k = 1
lr = 0.01
for i in range(100):
  yval.append(k)
  error = lr * grad(x, A, B, C)
  newxval = x - error
  x = newxval
  fval.append(function(x, A, B, C))

fval

1.0
[100 100 100]


[40173.60581134526,
 36854.81780463629,
 33999.45902268134,
 31557.674300485378,
 29383.28106814183,
 27528.64998514265,
 25935.740270601174,
 24529.08602497223,
 23321.78438014018,
 22197.72665275859,
 21223.96667990731,
 20338.697996776144,
 19540.296552033156,
 18818.993571311035,
 18151.80475422202,
 17550.501857401796,
 17036.64187417981,
 16559.976484524155,
 16095.597430949565,
 15622.231975494906,
 15185.467104002651,
 14806.410114579956,
 14408.779507852792,
 14066.189137964222,
 13730.914962636874,
 13376.241401067125,
 13065.579917819792,
 12743.694018683156,
 12456.952202867935,
 12150.551702063614,
 11872.364726470727,
 11574.685392101124,
 11307.388966875675,
 11021.529289785332,
 10768.68121839116,
 10503.817475037567,
 10245.966607745375,
 10006.972943911807,
 9759.117891395379,
 9534.902973155533,
 9310.221426681897,
 9074.12248481041,
 8870.550317243376,
 8650.003259837578,
 8441.356412130795,
 8240.707022765035,
 8043.393100136836,
 7840.002604730849,
 7661.920759164